import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().default(3000),
  APP_WEB_URL: Joi.string().uri().optional(),
  APP_FRONTEND_URL: Joi.string().uri().optional(),
  BILLING_EOD_CRON: Joi.string().default('55 23 * * *'),
  INVOICE_REMINDER_CRON: Joi.string().default('0 8 * * *'),
  HOLIDAY_API_BASE_URL: Joi.string().uri().optional(),
  HOLIDAY_API_COUNTRY_CODE: Joi.string().length(2).optional(),
  DATABASE_URL: Joi.string().uri({ scheme: ['postgresql', 'postgres'] }).required(),
  JWT_SECRET: Joi.string().min(8).required(),
  JWT_EXPIRES_IN: Joi.string().default('5m'),
  POSTGRES_DB: Joi.string().default('kolekto_db'),
  POSTGRES_USER: Joi.string().default('kolekto'),
  POSTGRES_PASSWORD: Joi.string().default('kolekto_password'),
  REDIS_HOST: Joi.string().default('redis'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_DB: Joi.number().default(0),
  QUEUE_PREFIX: Joi.string().default('kolekto'),
  QUEUE_REMOVE_ON_COMPLETE: Joi.number().default(100),
  QUEUE_REMOVE_ON_FAIL: Joi.number().default(500),
  LOG_DIR: Joi.string().default('logs'),
  LOG_RETENTION_DAYS: Joi.number().min(1).default(14),
  MINIO_ENDPOINT: Joi.string().required(),
  MINIO_PORT: Joi.number().default(9000),
  MINIO_ACCESS_KEY: Joi.string().required(),
  MINIO_SECRET_KEY: Joi.string().required(),
  MINIO_BUCKET: Joi.string().required(),
  MINIO_USE_SSL: Joi.boolean().truthy('true').falsy('false').default(false),
  MINIO_REGION: Joi.string().default('us-east-1'),
  MINIO_PUBLIC_URL: Joi.string().uri().optional(),
  UPLOAD_MAX_SIZE_MB: Joi.number().min(1).max(20).default(5),
  SMTP_HOST: Joi.string().optional(),
  SMTP_PORT: Joi.number().default(587),
  SMTP_SECURE: Joi.boolean().truthy('true').falsy('false').default(false),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASS: Joi.string().allow('').optional(),
  SMTP_FROM: Joi.string().default('Kolekto <noreply@kolekto.id>'),
});
